baseURL = "https://wassp.dev/"
languageCode = "en-us"
title = "/dev/wassp"

disableKinds = ["taxonomy", "term"]

[params]
  author = "wassp"
  description = "Systems programming, Rust, industrial protocols, and optimization"
  tagline = "blogs here, when he blogs."

[markup.highlight]
  style = "monokai"
  lineNos = true

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "archive"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2

[permalinks]
  posts = "/posts/:slug/"
